version: '3.1'
services:
  ewm-service:
    build: ewm-service
    image: ewm_service_image
    container_name: ewm_container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
      - SPRING_DATASOURCE_USERNAME=ewmSrv
      - SPRING_DATASOURCE_PASSWORD=ewmSrv
      - STATS_SERVER_URL=http://stats-server:9090

  ewm-db:
    image: postgres:latest
    container_name: ewm_db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=ewmSrv
      - POSTGRES_PASSWORD=ewmSrv

  stats-server:
    build: stats-service/stats-server
    image: stats_server_image
    container_name: stats_container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING_DATASOURCE_USERNAME=statsSrv
      - SPRING_DATASOURCE_PASSWORD=statsSrv

  stats-db:
    image: postgres:latest
    container_name: stats_db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=statsSrv
      - POSTGRES_PASSWORD=statsSrv